apiVersion: apps/v1
kind: Deployment
metadata:
  name: agi-service
  labels:
    app: agi-service
    version: v4.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agi-service
  template:
    metadata:
      labels:
        app: agi-service
    spec:
      containers:
      - name: agi-service
        image: vedhavriddhi/agi-service:4.0.0
        ports:
        - containerPort: 8201
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: agi-secrets
              key: openai_key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: agi_db_url
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8201
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8201
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: agi-service-svc
spec:
  selector:
    app: agi-service
  ports:
  - protocol: TCP
    port: 8201
    targetPort: 8201
  type: ClusterIP
