apiVersion: apps/v1
kind: Deployment
metadata:
  name: defi-service
  labels:
    app: defi-service
    version: v4.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defi-service
  template:
    metadata:
      labels:
        app: defi-service
    spec:
      containers:
      - name: defi-service
        image: vedhavriddhi/defi-service:4.0.0
        ports:
        - containerPort: 8202
        env:
        - name: WEB3_PROVIDER
          valueFrom:
            secretKeyRef:
              name: defi-secrets
              key: web3_provider
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: defi_db_url
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8202
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8202
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: defi-service-svc
spec:
  selector:
    app: defi-service
  ports:
  - protocol: TCP
    port: 8202
    targetPort: 8202
  type: ClusterIP
