apiVersion: apps/v1
kind: Deployment
metadata:
  name: vedhavriddhi-risk-service
  labels:
    app: vedhavriddhi-risk
    version: v2.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vedhavriddhi-risk
  template:
    metadata:
      labels:
        app: vedhavriddhi-risk
        version: v2.0.0
    spec:
      containers:
      - name: risk-service
        image: vedhavriddhi/risk-service:2.0.0
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vedhavriddhi-secrets
              key: risk-db-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: vedhavriddhi-secrets
              key: redis-url
        - name: TIMESERIES_DB_URL
          valueFrom:
            secretKeyRef:
              name: vedhavriddhi-secrets
              key: timeseries-db-url
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vedhavriddhi-risk-service
  labels:
    app: vedhavriddhi-risk
spec:
  selector:
    app: vedhavriddhi-risk
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
  type: ClusterIP
